version: '3.8'

services:
  hadoop-namenode:
    image: apache/hadoop:3.3.5
    hostname: hadoop-namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870 # Node Manager UI
    env_file:
      - ./hadoop/config/config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - type: bind
        source: ./hadoop/namenode
        target: /etc/hadoop
    networks:
      - lakehouse-net

  hadoop-datanode:
    image: apache/hadoop:3.3.5
    command: ["hdfs", "datanode"]
    env_file:
      - ./hadoop/config/config 
    networks:
      - lakehouse-net

  hadoop-resourcemanager:
    image: apache/hadoop:3.3.5
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088 # Hadoop Cluster Manager UI
    env_file:
      - ./hadoop/config/config
    volumes:
      - ./test.sh:/opt/test.sh
    networks:
      - lakehouse-net

  hadoop-nodemanager:
    image: apache/hadoop:3.3.5
    command: ["yarn", "nodemanager"]
    env_file:
      - ./hadoop/config/config
    networks:
      - lakehouse-net

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./spark/master/data:/bitnami/spark
      - ./hadoop/config:/etc/hadoop/conf
    networks:
      - lakehouse-net
    depends_on:
      - hadoop-namenode

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    hostname: spark-worker
    ports:
      - "8081:8081"  # Spark Worker UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./spark/worker/data:/bitnami/spark
      - ./hadoop/config:/etc/hadoop/conf
    networks:
      - lakehouse-net
    depends_on:
      - spark-master

  trino:
    image: trinodb/trino:latest
    container_name: trino
    hostname: trino
    ports:
      - "8082:8080"  # Trino Web UI
    environment:
      - JAVA_TOOL_OPTIONS=-Dnode.environment=production -Dnode.id=trino -Dnode.data-dir=/data
    volumes:
      - ./trino/config:/etc/trino
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/data:/data
    networks:
      - lakehouse-net
    depends_on:
      - hadoop-namenode

networks:
  lakehouse-net:
    driver: bridge

volumes:
  namenode_data:
  datanode_data:
